version: "3.4"

networks:
  server:
    driver: bridge

services:
  reverseproxy:
    networks:
      - server
    depends_on:
      - portfolio
      - chat
      - webstoreclient
      - trackerclient
      - tabledemo
      - itemlist
      - music
      - ghostNick
    build: .
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.data/ssl:/etc/letsencrypt

  portfolio:
    networks:
      - server
    restart: always
    build: ../portfolio

  chat:
    networks:
      - server
    restart: always
    build: ../Nick-Chat
  
  tabledemo:
    networks:
      - server
    restart: always
    build: ../tableDemo
    
  webstoreclient:
    networks:
      - server
    restart: always
    build: ../webstore/client
    links:
      - webstoreapi
    volumes:
      - /root/projects/webstore/client/public/images:/public/images
    depends_on: 
      - webstoreapi

  webstoreapi:
    networks:
      - server
    restart: always
    build: ../webstore/api
    depends_on: 
      - mongo
    volumes:
      - /root/projects/webstore/client/public/images:/images
    environment: 
      - MONGODB_URI=mongo/webstore
      - SESS_SECRET=session!secret
      - SESS_NAME=session
      - NODE_ENV=production
      - TEST_STRIPE_PUBLIC_KEY=pk_test_ZsI61lf4ShVcQxUfyEuwXAil001sxzJmMh
      - TEST_STRIPE_SECRET_KEY=sk_test_HxyAAa6zn1PYlnqzEto3rxYK00Mxet9Llp

  itemlistapi:
    networks:
      - server
    build: ../itemlist-demo/api
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo/itemlist
      - PORT=4000
      - SOURCE=https://itemlist.bairdjames.com

  itemlist:
    networks:
      - server
    restart: always
    build: ../itemlist-demo/client
    links:
      - itemlistapi
    depends_on:
      - itemlistapi
    environment:
      - REACT_APP_BASE_SERVER=itemlistapi:4000
      - REACT_APP_FIREBASE_APIKEY=
      - REACT_APP_FIREBASE_AUTHDOMAIN=
      - REACT_APP_FIREBASE_DATABASEURL=
      - REACT_APP_FIREBASE_PROJECTID=
      - REACT_APP_FIREBASE_STORAGEBUCKET=
      - REACT_APP_FIREBASE_MESSAGINGSENDERID=
      - REACT_APP_FIREBASE_APPID=

  trackerapi:
    networks:
      - server
    build: ../crypto-tracker/api
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo/tracker
      - NODE_ENV=production
      - PORT=4000
      - SESS_SECRET=do not lick the spoons
      - SESS_NAME=user-session

  trackerclient:
    networks:
      - server
    restart: always
    build: ../crypto-tracker/client
    links:
      - trackerapi
    depends_on:
      - trackerapi

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=0
      - USER_GID=0
      - GITEA__database__DB_TYPE=postgres
+     - GITEA__database__HOST=postgres:5432
+     - GITEA__database__NAME=gitea
+     - GITEA__database__USER=postgres
+     - GITEA__database__PASSWD=TnDY2Mg7dvrZeWW452ZkKYc6UF6ymVr9
    restart: always
    networks:
      - gitea
    volumes:
      - ./.data/gitea:/data
      - ./.data/gitea/etc/timezone:/etc/timezone:ro
      - ./.data/gitea/etc/localtime:/etc/localtime:ro

  mongo:
    networks:
      - server
    image: mongo:4.2-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.data/mongo:/data/db
    command: mongod --quiet --logpath=/dev/null
  
  music:
    networks:
      - server
    restart: always
    build: ../musicNotifier
    depends_on:
      - postgres
    environment:
      - cookieSecret=thisisanothersecret
      - SEND_GRID_KEY=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
      - SPOTIFY_CLIENT_ID=6ab4c4ef356141da8fd2328435d7c6e1
      - SPOTIFY_CLIENT_SECRET=2b8f860292ab4eb0ac3542ac3d28bbe0
      - PORT=5000
      - NODE_ENV=production
      - DATABASE_URL='postgres://postgres:TnDY2Mg7dvrZeWW452ZkKYc6UF6ymVr9@postgres/notifier_prod'

  postgres:
    networks:
      - server
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=TnDY2Mg7dvrZeWW452ZkKYc6UF6ymVr9
      - POSTGRES_DB=notifier_prod
      - PGDATA=/var/lib/postgres
    volumes:
      - ./.data/pgdata:/var/lib/postgres

  ghostNick:
    networks:
      - server
    image: ghost:3-alpine
    restart: always
    depends_on:
      - mysql
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: ajklsdg0sAjn9a93jdg
      database__connection__database: ghostNick
      # this url value is just an example, and is likely wrong for your environment!
      url: http://blog.bairdjames.com

  mysql:
    networks:
      - server
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ajklsdg0sAjn9a93jdg
    volumes:
      - ./.data/mysql:/var/lib/mysql