version: "3.5"

networks:
  server:
    driver: bridge

services:
  reverseproxy:
    networks:
      - server
    depends_on:
      - portfolio
      - chat
      - webstoreclient
      - trackerclient
      - tabledemo
      - itemlist
      - music
      - ghostNick
      - wekan
    build: .
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./.data/ssl:/etc/letsencrypt

  portfolio:
    networks:
      - server
    restart: always
    build: ../portfolio

  chat:
    networks:
      - server
    restart: always
    build: ../Nick-Chat
  
  tabledemo:
    networks:
      - server
    restart: always
    build: ../tableDemo
    
  webstoreclient:
    networks:
      - server
    restart: always
    build: ../webstore/client
    links:
      - webstoreapi
    volumes:
      - /root/projects/webstore/client/public/images:/public/images
    depends_on: 
      - webstoreapi

  webstoreapi:
    networks:
      - server
    restart: always
    build: ../webstore/api
    depends_on: 
      - mongo
    volumes:
      - /root/projects/webstore/client/public/images:/images
    environment: 
      - MONGODB_URI=mongo/webstore
      - SESS_SECRET=session!secret
      - SESS_NAME=session
      - NODE_ENV=production
      - TEST_STRIPE_PUBLIC_KEY=pk_test_ZsI61lf4ShVcQxUfyEuwXAil001sxzJmMh
      - TEST_STRIPE_SECRET_KEY=sk_test_HxyAAa6zn1PYlnqzEto3rxYK00Mxet9Llp

  itemlistapi:
    networks:
      - server
    build: ../itemlist-demo/api
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo/itemlist
      - PORT=4000
      - SOURCE=https://itemlist.bairdjames.com

  itemlist:
    networks:
      - server
    restart: always
    build: ../itemlist-demo/client
    links:
      - itemlistapi
    depends_on:
      - itemlistapi
    environment:
      - REACT_APP_BASE_SERVER=itemlistapi:4000
      - REACT_APP_FIREBASE_APIKEY=
      - REACT_APP_FIREBASE_AUTHDOMAIN=
      - REACT_APP_FIREBASE_DATABASEURL=
      - REACT_APP_FIREBASE_PROJECTID=
      - REACT_APP_FIREBASE_STORAGEBUCKET=
      - REACT_APP_FIREBASE_MESSAGINGSENDERID=
      - REACT_APP_FIREBASE_APPID=

  trackerapi:
    networks:
      - server
    build: ../crypto-tracker/api
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongo/tracker
      - NODE_ENV=production
      - PORT=4000
      - SESS_SECRET=do not lick the spoons
      - SESS_NAME=user-session

  trackerclient:
    networks:
      - server
    restart: always
    build: ../crypto-tracker/client
    links:
      - trackerapi
    depends_on:
      - trackerapi

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=postgres
      - GITEA__database__PASSWD=TnDY2Mg7dvrZeWW452ZkKYc6UF6ymVr9
    restart: always
    networks:
      - server
    volumes:
      - ./.data/gitea:/data
      - ./.data/gitea/etc/timezone:/etc/timezone:ro
      - ./.data/gitea/etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres

  mongo:
    networks:
      - server
    image: mongo:4.2-bionic
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./.data/mongo:/data/db
    command: mongod --quiet --logpath=/dev/null
  
  music:
    networks:
      - server
    restart: always
    build: ../musicNotifier
    depends_on:
      - postgres
    environment:
      - cookieSecret=thisisanothersecret
      - SEND_GRID_KEY=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
      - SPOTIFY_CLIENT_ID=6ab4c4ef356141da8fd2328435d7c6e1
      - SPOTIFY_CLIENT_SECRET=2b8f860292ab4eb0ac3542ac3d28bbe0
      - PORT=5000
      - NODE_ENV=production
      - DATABASE_URL='postgres://postgres:TnDY2Mg7dvrZeWW452ZkKYc6UF6ymVr9@postgres/notifier_prod'

  postgres:
    networks:
      - server
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=TnDY2Mg7dvrZeWW452ZkKYc6UF6ymVr9
      - POSTGRES_DB=notifier_prod
      - PGDATA=/var/lib/postgres
    volumes:
      - ./.data/pgdata:/var/lib/postgres

  ghostNick:
    networks:
      - server
    image: ghost:3-alpine
    restart: always
    depends_on:
      - mysql
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: ajklsdg0sAjn9a93jdg
      database__connection__database: ghostNick
      # this url value is just an example, and is likely wrong for your environment!
      url: http://blog.bairdjames.com

  mysql:
    networks:
      - server
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ajklsdg0sAjn9a93jdg
    volumes:
      - ./.data/mysql:/var/lib/mysql

  wekan-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wekan-app
    security_opt:
      - seccomp:unconfined
    restart: always
    networks:
      - server
    environment:
      - BUILD_DEPS="apt-utils libarchive-tools gnupg gosu wget curl bzip2 g++ build-essential git ca-certificates python3"
      - DEBUG=false
      - NODE_VERSION=v14.20.0
      - METEOR_RELEASE=1.10.2
      - USE_EDGE=false
      - METEOR_EDGE=1.5-beta.17
      - NPM_VERSION=latest
      - FIBERS_VERSION=4.0.1
      - ARCHITECTURE=linux-x64
      - SRC_PATH=./
      - RESULTS_PER_PAGE=""
      - ACCOUNTS_LOCKOUT_KNOWN_USERS_FAILURES_BEFORE=3
      - ACCOUNTS_LOCKOUT_KNOWN_USERS_PERIOD=60
      - ACCOUNTS_LOCKOUT_KNOWN_USERS_FAILURE_WINDOW=15
      - ACCOUNTS_LOCKOUT_UNKNOWN_USERS_FAILURES_BERORE=3
      - ACCOUNTS_LOCKOUT_UNKNOWN_USERS_LOCKOUT_PERIOD=60
      - ACCOUNTS_LOCKOUT_UNKNOWN_USERS_FAILURE_WINDOW=15
      - ACCOUNTS_COMMON_LOGIN_EXPIRATION_IN_DAYS=90
      - ATTACHMENTS_UPLOAD_EXTERNAL_PROGRAM=""
      - ATTACHMENTS_UPLOAD_MIME_TYPES=""
      - ATTACHMENTS_UPLOAD_MAX_SIZE=0
      - AVATARS_UPLOAD_EXTERNAL_PROGRAM=""
      - AVATARS_UPLOAD_MIME_TYPES=""
      - AVATARS_UPLOAD_MAX_SIZE=0
      - MAX_IMAGE_PIXEL=""
      - IMAGE_COMPRESS_RATIO=""
      - NOTIFICATION_TRAY_AFTER_READ_DAYS_BEFORE_REMOVE=""
      - NOTIFY_DUE_DAYS_BEFORE_AND_AFTER=""
      - NOTIFY_DUE_AT_HOUR_OF_DAY=""
      - EMAIL_NOTIFICATION_TIMEOUT=30000
      - MATOMO_ADDRESS=""
      - MATOMO_SITE_ID=""
      - MATOMO_DO_NOT_TRACK=true
      - MATOMO_WITH_USERNAME=false
      - TRUSTED_URL=""
      - WEBHOOKS_ATTRIBUTES=""
      - OAUTH2_ENABLED=false
      - OIDC_REDIRECTION_ENABLED=false
      - OAUTH2_CA_CERT=""
      - OAUTH2_ADFS_ENABLED=false
      - OAUTH2_LOGIN_STYLE=redirect
      - OAUTH2_CLIENT_ID=""
      - OAUTH2_SECRET=""
      - OAUTH2_SERVER_URL=""
      - OAUTH2_AUTH_ENDPOINT=""
      - OAUTH2_USERINFO_ENDPOINT=""
      - OAUTH2_TOKEN_ENDPOINT=""
      - OAUTH2_ID_MAP=""
      - OAUTH2_USERNAME_MAP=""
      - OAUTH2_FULLNAME_MAP=""
      - OAUTH2_ID_TOKEN_WHITELIST_FIELDS=""
      - OAUTH2_REQUEST_PERMISSIONS='openid profile email'
      - OAUTH2_EMAIL_MAP=""
      - LDAP_ENABLE=false
      - LDAP_PORT=389
      - LDAP_HOST=""
      - LDAP_AD_SIMPLE_AUTH=""
      - LDAP_USER_AUTHENTICATION=false
      - LDAP_USER_AUTHENTICATION_FIELD=uid
      - LDAP_BASEDN=""
      - LDAP_LOGIN_FALLBACK=false
      - LDAP_RECONNECT=true
      - LDAP_TIMEOUT=10000
      - LDAP_IDLE_TIMEOUT=10000
      - LDAP_CONNECT_TIMEOUT=10000
      - LDAP_AUTHENTIFICATION=false
      - LDAP_AUTHENTIFICATION_USERDN=""
      - LDAP_AUTHENTIFICATION_PASSWORD=""
      - LDAP_LOG_ENABLED=false
      - LDAP_BACKGROUND_SYNC=false
      - LDAP_BACKGROUND_SYNC_INTERVAL=""
      - LDAP_BACKGROUND_SYNC_KEEP_EXISTANT_USERS_UPDATED=false
      - LDAP_BACKGROUND_SYNC_IMPORT_NEW_USERS=false
      - LDAP_ENCRYPTION=false
      - LDAP_CA_CERT=""
      - LDAP_REJECT_UNAUTHORIZED=false
      - LDAP_USER_SEARCH_FILTER=""
      - LDAP_USER_SEARCH_SCOPE=""
      - LDAP_USER_SEARCH_FIELD=""
      - LDAP_SEARCH_PAGE_SIZE=0
      - LDAP_SEARCH_SIZE_LIMIT=0
      - LDAP_GROUP_FILTER_ENABLE=false
      - LDAP_GROUP_FILTER_OBJECTCLASS=""
      - LDAP_GROUP_FILTER_GROUP_ID_ATTRIBUTE=""
      - LDAP_GROUP_FILTER_GROUP_MEMBER_ATTRIBUTE=""
      - LDAP_GROUP_FILTER_GROUP_MEMBER_FORMAT=""
      - LDAP_GROUP_FILTER_GROUP_NAME=""
      - LDAP_UNIQUE_IDENTIFIER_FIELD=""
      - LDAP_UTF8_NAMES_SLUGIFY=true
      - LDAP_USERNAME_FIELD=""
      - LDAP_FULLNAME_FIELD=""
      - LDAP_MERGE_EXISTING_USERS=false
      - LDAP_EMAIL_FIELD=""
      - LDAP_EMAIL_MATCH_ENABLE=false
      - LDAP_EMAIL_MATCH_REQUIRE=false
      - LDAP_EMAIL_MATCH_VERIFIED=false
      - LDAP_SYNC_USER_DATA=false
      - LDAP_SYNC_USER_DATA_FIELDMAP=""
      - LDAP_SYNC_GROUP_ROLES=""
      - LDAP_DEFAULT_DOMAIN=""
      - LDAP_SYNC_ADMIN_STATUS=""
      - LDAP_SYNC_ADMIN_GROUPS=""
      - HEADER_LOGIN_ID=""
      - HEADER_LOGIN_FIRSTNAME=""
      - HEADER_LOGIN_LASTNAME=""
      - HEADER_LOGIN_EMAIL=""
      - LOGOUT_WITH_TIMER=false
      - LOGOUT_IN=""
      - LOGOUT_ON_HOURS=""
      - LOGOUT_ON_MINUTES=""
      - CORS=""
      - CORS_ALLOW_HEADERS=""
      - CORS_EXPOSE_HEADERS=""
      - DEFAULT_AUTHENTICATION_METHOD=""
      - PASSWORD_LOGIN_ENABLED=true
      - CAS_ENABLED=false
      - CAS_BASE_URL=""
      - CAS_LOGIN_URL=""
      - CAS_VALIDATE_URL=""
      - SAML_ENABLED=false
      - SAML_PROVIDER=""
      - SAML_ENTRYPOINT=""
      - SAML_ISSUER=""
      - SAML_CERT=""
      - SAML_IDPSLO_REDIRECTURL=""
      - SAML_PRIVATE_KEYFILE=""
      - SAML_PUBLIC_CERTFILE=""
      - SAML_IDENTIFIER_FORMAT=""
      - SAML_LOCAL_PROFILE_MATCH_ATTRIBUTE=""
      - SAML_ATTRIBUTES=""
      - ORACLE_OIM_ENABLED=false
      - WAIT_SPINNER=""
      - NODE_OPTIONS="--max_old_space_size=4096"
      - WRITABLE_PATH=/data
      - MONGO_URL=mongodb://mongo:27017/wekan
      - ROOT_URL=https://kanban.bairdjames.com  #   <=== using only at same laptop/desktop where Wekan is installed
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.data/wekan/wekan-files:/data:rw
      - ./.data/wekan/attachments:/data/attachments

